---
persister:
  name: file
  file:
    dir: ./state/
watchers:
  # - name: journald
  #   processors:
  #     - name: log
  - name: docker
    processors:
      - name: log
        log:
          format: json
