---
matcher_golang_panic: &matcher_golang_panic
  start_line:
    type: expr
    expr: '(pre "panic:")'
  end_line:
    type: expr
    expr: '
      (not
        (or
          (eq "")
          (pre "goroutine ")
          (re ".*\\.[A-Za-z0-9](.*)$")
          (pre "        ")
        )
      )
    '
  include_end: false
  group_by:
    - '_PID'
  max_lines: 50

actions:
  action_log:
    type: log
    log:
      format:
        type: plain
  action_notify:
    type: notify
    notify:
      title_format:
        type: template
        template:
          format: 'Service {SYSLOG_IDENTIFIER} on {_HOSTNAME} panicked at {$timestamp}'
      body_format:
        type: plain
      max_title_size: 150
      max_body_size: 2048
      services:
        - type: 'telegram'
          telegram:
            token: '' # Telegram Token
            receivers:
              - -100 # Telegram chat ID

actions:
  action_log:
    type: log
    log:
      format: plain
persister:
  type: file
  file:
    dir: ./state/
processors:
  proc_log:
    type: matcher
    action: action_log
    # matcher: *matcher_golang_panic
    matcher:
      start_line:
        type: any
readers:
  - id: journald
    type: journald
    processors:
      - proc_log
    initial_state:
      timestamp: "2022-04-01T00:00:00Z"
  # - id: docker
  #   type: docker
  #   processors:
  #     - proc_log
