---
actions:
  action_log:
    type: log
    log:
      format: json
persister:
  type: file
  file:
    dir: ./state/
processors:
  proc_log:
    type: matcher
    action: action_log
    matcher:
      start_line:
        type: any
        # type: substring
        # substring: container
readers:
  - id: journald
    type: journald
    processors:
      - proc_log
    initial_state:
      timestamp: "2022-04-01T00:00:00Z"
  - id: docker
    type: docker
    processors:
      - proc_log
